### МАИ
### ФИО студента: Меркулов Лев Владимирович
### группа: Т120-101М-20
### ФИО руководителя: Поповкин Александр Викторович
### дата: 29.10.2020
### Numpy, Лаб раб № 3
### Москва, 2020 г.

In [2]:
import numpy as np

1.Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
arr = np.array([1,2,3,4,5])

arr_new = np.zeros(len(arr) + (len(arr)-1)*3)
arr_new[::3+1] = arr
arr_new

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

2.Поменять 2 строки в матрице

In [5]:
A = np.arange(25).reshape(5,5)
print(A, '\n')
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


3.Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [6]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)

G


array([( 0, 21), ( 0, 99), ( 1, 73), ( 1, 97), ( 2, 41), ( 2, 71),
       ( 4, 23), ( 4, 46), (13, 28), (13, 52), (21, 99), (22, 44),
       (22, 73), (23, 46), (26, 61), (26, 99), (28, 52), (29, 62),
       (29, 79), (30, 78), (30, 85), (30, 98), (30, 99), (41, 71),
       (44, 73), (61, 99), (62, 79), (73, 97), (78, 99), (85, 98)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

4.Дан массив C; создать массив A, что np.bincount(A) == C

In [7]:
C = np.bincount([1,1,2,3,4,4,6])

np.repeat(np.arange(len(C)), C)

array([1, 1, 2, 3, 4, 4, 6])

5.Посчитать среднее, используя плавающее окно

In [13]:
def moving_average(a, n = 3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(10), 3))

[1. 2. 3. 4. 5. 6. 7. 8.]


6.Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [14]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


7.Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [18]:
Z = np.random.randint(0,2,100)
np.logical_not(arr, out = arr)

array([1, 1, 1, 1, 1])

In [19]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([-1, -1, -1, -1, -1])

8.Посчитать ранг матрицы

In [29]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


9.Найти наиболее частое значение в массиве

In [33]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[6 8 7 7 3 8 4 3 0 3 7 2 1 6 4 4 4 4 1 4 9 6 3 3 1 5 8 5 1 7 4 2 4 2 3 3 8
 2 1 6 4 8 7 3 1 9 1 5 1 0]
4


10.Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [40]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[1, 4, 2],
         [2, 1, 3],
         [3, 0, 0]],

        [[4, 2, 1],
         [1, 3, 1],
         [0, 0, 4]],

        [[2, 1, 0],
         [3, 1, 0],
         [0, 4, 0]],

        [[1, 0, 1],
         [1, 0, 2],
         [4, 0, 4]],

        [[0, 1, 2],
         [0, 2, 0],
         [0, 4, 4]],

        [[1, 2, 2],
         [2, 0, 4],
         [4, 4, 3]],

        [[2, 2, 0],
         [0, 4, 4],
         [4, 3, 2]],

        [[2, 0, 0],
         [4, 4, 2],
         [3, 2, 0]]],


       [[[2, 1, 3],
         [3, 0, 0],
         [2, 0, 4]],

        [[1, 3, 1],
         [0, 0, 4],
         [0, 4, 0]],

        [[3, 1, 0],
         [0, 4, 0],
         [4, 0, 2]],

        [[1, 0, 2],
         [4, 0, 4],
         [0, 2, 2]],

        [[0, 2, 0],
         [0, 4, 4],
         [2, 2, 3]],

        [[2, 0, 4],
         [4, 4, 3],
         [2, 3, 0]],

        [[0, 4, 4],
         [4, 3, 2],
         [3, 0, 2]],

        [[4, 4, 2],
         [3, 2, 0],
         [0, 2, 3]]],


    

11.Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [37]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

12.Дан массив 16x16, посчитать сумму по блокам 4x4

In [39]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

13.Найти n наибольших значений в массиве

In [42]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9998 9996 9995]


14.Построить прямое произведение массивов (все комбинации с каждым элементом)

In [44]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


15.Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [45]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 3 5 6]


16.Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [47]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z, '\n')
print(U)

[[1 0 4]
 [3 1 1]
 [1 2 4]
 [3 1 4]
 [0 3 2]
 [0 4 3]
 [1 2 4]
 [3 0 2]
 [1 2 0]
 [3 1 0]] 

[[1 0 4]
 [3 1 1]
 [1 2 4]
 [3 1 4]
 [0 3 2]
 [0 4 3]
 [1 2 4]
 [3 0 2]
 [1 2 0]
 [3 1 0]]


17.Преобразовать вектор чисел в матрицу бинарных представлений

In [49]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


18.Дан двумерный массив. Найти все различные строки

In [50]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


19.Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [53]:
# Useful docs for einsum -> http://ajcr.net/Basic-guide-to-einsum/

A = np.random.random((10,))
B = np.random.random((10,))

np.einsum('i->', A)       # np.sum(A)


4.708571830464958

In [54]:
np.einsum('i,i->i', A, B) # A * B


array([0.07637126, 0.00158144, 0.11854638, 0.49958688, 0.05570558,
       0.03633975, 0.27394832, 0.03101302, 0.13105284, 0.65210247])

In [55]:
np.einsum('i,i', A, B)    # np.inner(A, B)

1.876247943376812

In [56]:
np.einsum('i,j', A, B)    # np.outer(A, B)

array([[7.63712641e-02, 2.87337359e-01, 8.16901703e-02, 2.31911356e-01,
        6.19833566e-02, 2.91746817e-02, 2.77146976e-01, 8.72930187e-02,
        5.26387869e-02, 2.94393464e-01],
       [4.20330632e-04, 1.58144160e-03, 4.49604721e-04, 1.27638907e-03,
        3.41142755e-04, 1.60571028e-04, 1.52535597e-03, 4.80441566e-04,
        2.89712300e-04, 1.62027684e-03],
       [1.10827742e-01, 4.16975561e-01, 1.18546383e-01, 3.36542969e-01,
        8.99484318e-02, 4.23374437e-02, 4.02187575e-01, 1.26677072e-01,
        7.63878660e-02, 4.27215173e-01],
       [1.64520108e-01, 6.18986394e-01, 1.75978174e-01, 4.99586878e-01,
        1.33525464e-01, 6.28485313e-02, 5.97034119e-01, 1.88047913e-01,
        1.13395254e-01, 6.34186758e-01],
       [6.86362549e-02, 2.58235352e-01, 7.34164535e-02, 2.08422987e-01,
        5.57055787e-02, 2.62198212e-02, 2.49077068e-01, 7.84518360e-02,
        4.73074426e-02, 2.64576802e-01],
       [9.51274250e-02, 3.57905077e-01, 1.01752611e-01, 2.88866898e-01,
   