### МАИ
### ФИО студента: Меркулов Лев Владимирович
### группа: Т120-101М-20
### ФИО руководителя: Поповкин Александр Викторович
### дата: 26.11.2020
### Pandas, Лаб раб № 3
### Москва, 2020 г.

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

- Найти евклидово расстоняие между двумя объектами Series

In [4]:
a = pd.Series(np.array([1,2,3]))
b = pd.Series(np.array([4,5,6]))
np.linalg.norm(a-b)

5.196152422706632

- Найти индексы локальных максимумов в объекте Series

In [7]:
s = pd.Series([1, 5, 7, 20, 11])
dd = np.diff(np.sign(np.diff(s))) #discrete difference S[i+1] - S[i];

print(np.diff(s), np.sign(np.diff(s)), dd, sep = '\n\n') #n=1 by default
np.where(dd == -2)[0] + 1 #20

[ 4  2 13 -9]

[ 1  1  1 -1]

[ 0  0 -2]


array([3])

- Заменить пробелы наименее часто встречающимся символов

In [78]:
sentence = 'The quick brown fox jumps over the lazy dog'
s = pd.Series(list(sentence))
f = s.value_counts()
print(s.value_counts()) #show unique symbols
('').join(s.replace(' ', f.index[-1]))

     8
o    4
e    3
u    2
h    2
r    2
i    1
b    1
v    1
j    1
m    1
t    1
n    1
g    1
k    1
z    1
c    1
p    1
l    1
d    1
q    1
y    1
w    1
x    1
a    1
f    1
T    1
s    1
dtype: int64


'Thesquicksbrownsfoxsjumpssoverstheslazysdog'

- Создать объект Series, который содержит в индексах даты выходных дней субботы, а в значениях случайные числа от 1 до 10

In [94]:
pd.Series(np.random.randint(1,10,5), index = pd.date_range(start = '11/1/2020', freq = 'W-SAT', periods = 5))


2020-11-07    3
2020-11-14    1
2020-11-21    5
2020-11-28    9
2020-12-05    1
Freq: W-SAT, dtype: int64

- Заполнить пропущенные даты, значением выше (заполненной даты)

In [38]:
df = pd.DataFrame({"Date": [2, 5, 8, None, 10]}, index = pd.to_datetime(['2018-01-01', '2018-01-03', '2018-01-06', '2018-01-08', '2018-01-10']))
# bfill() - backward fill the missing values. ffill() - forward fill
print(df, df.bfill(), df.ffill(), sep = '\n\n')

            Date
2018-01-01   2.0
2018-01-03   5.0
2018-01-06   8.0
2018-01-08   NaN
2018-01-10  10.0

            Date
2018-01-01   2.0
2018-01-03   5.0
2018-01-06   8.0
2018-01-08  10.0
2018-01-10  10.0

            Date
2018-01-01   2.0
2018-01-03   5.0
2018-01-06   8.0
2018-01-08   8.0
2018-01-10  10.0


- Вычислить автокорреляцию объекта Series

In [5]:
s = pd.Series([0.25, 0.5, 0.2, -0.05])
s.autocorr()  

0.1035526330902407